import { useFormatting } from '../../hooks/useFormatting';

/**
 * Print-only footer component for reports.
 * Displays "Generated by Terrava ERP • <Generated Date>"
 */
export function PrintFooter() {
  const { formatDate } = useFormatting();
  const generatedDate = formatDate(new Date());

  return (
    <div className="print-footer">
      <div className="text-xs text-gray-500">
        Generated by Terrava ERP • {generatedDate}
      </div>
    </div>
  );
}
