/**
 * Tenant localisation option lists (canonical value + display label).
 * Keep codes in sync with App\Support\TenantLocalisation (apps/api).
 */

export const TENANT_LOCALISATION_DEFAULTS = {
  currency_code: 'PKR',
  locale: 'en-PK',
  timezone: 'Asia/Karachi',
} as const;

/** ISO 4217 code → friendly label (value stored = code only). */
export const CURRENCY_OPTIONS: { value: string; label: string }[] = [
  { value: 'PKR', label: 'Pakistani Rupee (PKR)' },
  { value: 'USD', label: 'US Dollar (USD)' },
  { value: 'GBP', label: 'British Pound (GBP)' },
  { value: 'EUR', label: 'Euro (EUR)' },
  { value: 'AED', label: 'UAE Dirham (AED)' },
  { value: 'SAR', label: 'Saudi Riyal (SAR)' },
  { value: 'INR', label: 'Indian Rupee (INR)' },
  { value: 'CNY', label: 'Chinese Yuan (CNY)' },
  { value: 'CAD', label: 'Canadian Dollar (CAD)' },
  { value: 'AUD', label: 'Australian Dollar (AUD)' },
  { value: 'NZD', label: 'New Zealand Dollar (NZD)' },
  { value: 'JPY', label: 'Japanese Yen (JPY)' },
  { value: 'CHF', label: 'Swiss Franc (CHF)' },
  { value: 'SGD', label: 'Singapore Dollar (SGD)' },
  { value: 'ZAR', label: 'South African Rand (ZAR)' },
  { value: 'TRY', label: 'Turkish Lira (TRY)' },
  { value: 'BHD', label: 'Bahraini Dinar (BHD)' },
  { value: 'QAR', label: 'Qatari Riyal (QAR)' },
  { value: 'KWD', label: 'Kuwaiti Dinar (KWD)' },
  { value: 'OMR', label: 'Omani Rial (OMR)' },
  { value: 'BDT', label: 'Bangladeshi Taka (BDT)' },
  { value: 'LKR', label: 'Sri Lankan Rupee (LKR)' },
  { value: 'NPR', label: 'Nepalese Rupee (NPR)' },
  { value: 'MVR', label: 'Maldivian Rufiyaa (MVR)' },
  { value: 'MYR', label: 'Malaysian Ringgit (MYR)' },
  { value: 'THB', label: 'Thai Baht (THB)' },
  { value: 'IDR', label: 'Indonesian Rupiah (IDR)' },
  { value: 'PHP', label: 'Philippine Peso (PHP)' },
  { value: 'VND', label: 'Vietnamese Dong (VND)' },
  { value: 'KRW', label: 'South Korean Won (KRW)' },
  { value: 'HKD', label: 'Hong Kong Dollar (HKD)' },
  { value: 'MXN', label: 'Mexican Peso (MXN)' },
  { value: 'BRL', label: 'Brazilian Real (BRL)' },
  { value: 'CLP', label: 'Chilean Peso (CLP)' },
  { value: 'COP', label: 'Colombian Peso (COP)' },
  { value: 'ARS', label: 'Argentine Peso (ARS)' },
  { value: 'PEN', label: 'Peruvian Sol (PEN)' },
  { value: 'EGP', label: 'Egyptian Pound (EGP)' },
  { value: 'NGN', label: 'Nigerian Naira (NGN)' },
  { value: 'KES', label: 'Kenyan Shilling (KES)' },
  { value: 'TZS', label: 'Tanzanian Shilling (TZS)' },
  { value: 'UGX', label: 'Ugandan Shilling (UGX)' },
  { value: 'MAD', label: 'Moroccan Dirham (MAD)' },
  { value: 'DZD', label: 'Algerian Dinar (DZD)' },
  { value: 'ILS', label: 'Israeli New Shekel (ILS)' },
  { value: 'SEK', label: 'Swedish Krona (SEK)' },
  { value: 'NOK', label: 'Norwegian Krone (NOK)' },
  { value: 'DKK', label: 'Danish Krone (DKK)' },
  { value: 'PLN', label: 'Polish Złoty (PLN)' },
  { value: 'CZK', label: 'Czech Koruna (CZK)' },
  { value: 'HUF', label: 'Hungarian Forint (HUF)' },
  { value: 'RON', label: 'Romanian Leu (RON)' },
  { value: 'BGN', label: 'Bulgarian Lev (BGN)' },
  { value: 'RUB', label: 'Russian Ruble (RUB)' },
  { value: 'UAH', label: 'Ukrainian Hryvnia (UAH)' },
  { value: 'KZT', label: 'Kazakhstani Tenge (KZT)' },
  { value: 'UZS', label: 'Uzbekistani Som (UZS)' },
  { value: 'GEL', label: 'Georgian Lari (GEL)' },
  { value: 'AMD', label: 'Armenian Dram (AMD)' },
  { value: 'AZN', label: 'Azerbaijani Manat (AZN)' },
  { value: 'BYN', label: 'Belarusian Ruble (BYN)' },
  { value: 'MDL', label: 'Moldovan Leu (MDL)' },
  { value: 'ALL', label: 'Albanian Lek (ALL)' },
  { value: 'TND', label: 'Tunisian Dinar (TND)' },
  { value: 'IQD', label: 'Iraqi Dinar (IQD)' },
  { value: 'JOD', label: 'Jordanian Dinar (JOD)' },
  { value: 'LBP', label: 'Lebanese Pound (LBP)' },
  { value: 'AFN', label: 'Afghan Afghani (AFN)' },
  { value: 'ETB', label: 'Ethiopian Birr (ETB)' },
  { value: 'GHS', label: 'Ghanaian Cedi (GHS)' },
  { value: 'ZMW', label: 'Zambian Kwacha (ZMW)' },
  { value: 'MZN', label: 'Mozambican Metical (MZN)' },
  { value: 'MWK', label: 'Malawian Kwacha (MWK)' },
  { value: 'XOF', label: 'West African CFA franc (XOF)' },
  { value: 'XAF', label: 'Central African CFA franc (XAF)' },
  { value: 'FJD', label: 'Fijian Dollar (FJD)' },
  { value: 'PGK', label: 'Papua New Guinean Kina (PGK)' },
  { value: 'SCR', label: 'Seychellois Rupee (SCR)' },
  { value: 'MUR', label: 'Mauritian Rupee (MUR)' },
  { value: 'BWP', label: 'Botswana Pula (BWP)' },
  { value: 'NAD', label: 'Namibian Dollar (NAD)' },
  { value: 'XPF', label: 'CFP franc (XPF)' },
  { value: 'WST', label: 'Samoan Tālā (WST)' },
  { value: 'TOP', label: 'Tongan Paʻanga (TOP)' },
  { value: 'VUV', label: 'Vanuatu Vatu (VUV)' },
].sort((a, b) => a.label.localeCompare(b.label));

/** BCP 47 locale tag (value stored = tag only). */
export const LOCALE_OPTIONS: { value: string; label: string }[] = [
  { value: 'en-PK', label: 'English (Pakistan) — en-PK' },
  { value: 'ur-PK', label: 'Urdu (Pakistan) — ur-PK' },
  { value: 'sd-PK', label: 'Sindhi (Pakistan) — sd-PK' },
  { value: 'en-GB', label: 'English (United Kingdom) — en-GB' },
  { value: 'en-US', label: 'English (United States) — en-US' },
  { value: 'en-AE', label: 'English (UAE) — en-AE' },
  { value: 'ar-AE', label: 'Arabic (UAE) — ar-AE' },
  { value: 'fr-FR', label: 'French (France) — fr-FR' },
  { value: 'de-DE', label: 'German (Germany) — de-DE' },
  { value: 'ar-SA', label: 'Arabic (Saudi Arabia) — ar-SA' },
  { value: 'hi-IN', label: 'Hindi (India) — hi-IN' },
  { value: 'bn-BD', label: 'Bangla (Bangladesh) — bn-BD' },
  { value: 'en-IN', label: 'English (India) — en-IN' },
  { value: 'si-LK', label: 'Sinhala (Sri Lanka) — si-LK' },
  { value: 'ne-NP', label: 'Nepali (Nepal) — ne-NP' },
  { value: 'dv-MV', label: 'Dhivehi (Maldives) — dv-MV' },
  { value: 'ms-MY', label: 'Malay (Malaysia) — ms-MY' },
  { value: 'id-ID', label: 'Indonesian (Indonesia) — id-ID' },
  { value: 'th-TH', label: 'Thai (Thailand) — th-TH' },
  { value: 'vi-VN', label: 'Vietnamese (Vietnam) — vi-VN' },
  { value: 'ja-JP', label: 'Japanese (Japan) — ja-JP' },
  { value: 'ko-KR', label: 'Korean (South Korea) — ko-KR' },
  { value: 'zh-CN', label: 'Chinese (China) — zh-CN' },
  { value: 'zh-HK', label: 'Chinese (Hong Kong) — zh-HK' },
  { value: 'zh-TW', label: 'Chinese (Taiwan) — zh-TW' },
  { value: 'es-ES', label: 'Spanish (Spain) — es-ES' },
  { value: 'es-MX', label: 'Spanish (Mexico) — es-MX' },
  { value: 'pt-BR', label: 'Portuguese (Brazil) — pt-BR' },
  { value: 'it-IT', label: 'Italian (Italy) — it-IT' },
  { value: 'nl-NL', label: 'Dutch (Netherlands) — nl-NL' },
  { value: 'sv-SE', label: 'Swedish (Sweden) — sv-SE' },
  { value: 'da-DK', label: 'Danish (Denmark) — da-DK' },
  { value: 'fi-FI', label: 'Finnish (Finland) — fi-FI' },
  { value: 'nb-NO', label: 'Norwegian Bokmål (Norway) — nb-NO' },
  { value: 'pl-PL', label: 'Polish (Poland) — pl-PL' },
  { value: 'cs-CZ', label: 'Czech (Czechia) — cs-CZ' },
  { value: 'hu-HU', label: 'Hungarian (Hungary) — hu-HU' },
  { value: 'ro-RO', label: 'Romanian (Romania) — ro-RO' },
  { value: 'el-GR', label: 'Greek (Greece) — el-GR' },
  { value: 'he-IL', label: 'Hebrew (Israel) — he-IL' },
  { value: 'tr-TR', label: 'Turkish (Türkiye) — tr-TR' },
  { value: 'fa-IR', label: 'Persian (Iran) — fa-IR' },
  { value: 'en-AU', label: 'English (Australia) — en-AU' },
  { value: 'en-NZ', label: 'English (New Zealand) — en-NZ' },
  { value: 'en-CA', label: 'English (Canada) — en-CA' },
  { value: 'fr-CA', label: 'French (Canada) — fr-CA' },
  { value: 'sw-KE', label: 'Swahili (Kenya) — sw-KE' },
  { value: 'am-ET', label: 'Amharic (Ethiopia) — am-ET' },
  { value: 'fr-SN', label: 'French (Senegal) — fr-SN' },
  { value: 'ar-EG', label: 'Arabic (Egypt) — ar-EG' },
  { value: 'en-ZA', label: 'English (South Africa) — en-ZA' },
  { value: 'pt-PT', label: 'Portuguese (Portugal) — pt-PT' },
].sort((a, b) => a.label.localeCompare(b.label));

/** IANA time zone ID (value stored = ID only). */
export const TIMEZONE_OPTIONS: { value: string; label: string }[] = [
  { value: 'UTC', label: 'UTC' },
  { value: 'Africa/Cairo', label: 'Africa/Cairo (Egypt)' },
  { value: 'Africa/Casablanca', label: 'Africa/Casablanca (Morocco)' },
  { value: 'Africa/Johannesburg', label: 'Africa/Johannesburg (South Africa)' },
  { value: 'Africa/Lagos', label: 'Africa/Lagos (Nigeria)' },
  { value: 'Africa/Nairobi', label: 'Africa/Nairobi (Kenya)' },
  { value: 'America/Bogota', label: 'America/Bogota (Colombia)' },
  { value: 'America/Buenos_Aires', label: 'America/Buenos_Aires (Argentina)' },
  { value: 'America/Caracas', label: 'America/Caracas (Venezuela)' },
  { value: 'America/Chicago', label: 'America/Chicago (US & Canada — Central)' },
  { value: 'America/Denver', label: 'America/Denver (US & Canada — Mountain)' },
  { value: 'America/Lima', label: 'America/Lima (Peru)' },
  { value: 'America/Los_Angeles', label: 'America/Los_Angeles (US & Canada — Pacific)' },
  { value: 'America/Mexico_City', label: 'America/Mexico_City (Mexico)' },
  { value: 'America/New_York', label: 'America/New_York (US & Canada — Eastern)' },
  { value: 'America/Santiago', label: 'America/Santiago (Chile)' },
  { value: 'America/Sao_Paulo', label: 'America/São Paulo (Brazil)' },
  { value: 'America/Toronto', label: 'America/Toronto (Canada — Eastern)' },
  { value: 'America/Vancouver', label: 'America/Vancouver (Canada — Pacific)' },
  { value: 'Asia/Aden', label: 'Asia/Aden (Yemen)' },
  { value: 'Asia/Almaty', label: 'Asia/Almaty (Kazakhstan)' },
  { value: 'Asia/Amman', label: 'Asia/Amman (Jordan)' },
  { value: 'Asia/Baghdad', label: 'Asia/Baghdad (Iraq)' },
  { value: 'Asia/Bahrain', label: 'Asia/Bahrain' },
  { value: 'Asia/Baku', label: 'Asia/Baku (Azerbaijan)' },
  { value: 'Asia/Bangkok', label: 'Asia/Bangkok (Thailand)' },
  { value: 'Asia/Beirut', label: 'Asia/Beirut (Lebanon)' },
  { value: 'Asia/Colombo', label: 'Asia/Colombo (Sri Lanka)' },
  { value: 'Asia/Dhaka', label: 'Asia/Dhaka (Bangladesh)' },
  { value: 'Asia/Dubai', label: 'Asia/Dubai (UAE)' },
  { value: 'Asia/Hong_Kong', label: 'Asia/Hong_Kong' },
  { value: 'Asia/Jakarta', label: 'Asia/Jakarta (Indonesia)' },
  { value: 'Asia/Jerusalem', label: 'Asia/Jerusalem' },
  { value: 'Asia/Kabul', label: 'Asia/Kabul (Afghanistan)' },
  { value: 'Asia/Karachi', label: 'Asia/Karachi (Pakistan)' },
  { value: 'Asia/Kathmandu', label: 'Asia/Kathmandu (Nepal)' },
  { value: 'Asia/Kolkata', label: 'Asia/Kolkata (India)' },
  { value: 'Asia/Kuala_Lumpur', label: 'Asia/Kuala_Lumpur (Malaysia)' },
  { value: 'Asia/Kuwait', label: 'Asia/Kuwait' },
  { value: 'Asia/Manila', label: 'Asia/Manila (Philippines)' },
  { value: 'Asia/Muscat', label: 'Asia/Muscat (Oman)' },
  { value: 'Asia/Qatar', label: 'Asia/Qatar' },
  { value: 'Asia/Riyadh', label: 'Asia/Riyadh (Saudi Arabia)' },
  { value: 'Asia/Seoul', label: 'Asia/Seoul (South Korea)' },
  { value: 'Asia/Shanghai', label: 'Asia/Shanghai (China)' },
  { value: 'Asia/Singapore', label: 'Asia/Singapore' },
  { value: 'Asia/Taipei', label: 'Asia/Taipei (Taiwan)' },
  { value: 'Asia/Tashkent', label: 'Asia/Tashkent (Uzbekistan)' },
  { value: 'Asia/Tehran', label: 'Asia/Tehran (Iran)' },
  { value: 'Asia/Tokyo', label: 'Asia/Tokyo (Japan)' },
  { value: 'Asia/Ulaanbaatar', label: 'Asia/Ulaanbaatar (Mongolia)' },
  { value: 'Asia/Yangon', label: 'Asia/Yangon (Myanmar)' },
  { value: 'Atlantic/Reykjavik', label: 'Atlantic/Reykjavik (Iceland)' },
  { value: 'Australia/Sydney', label: 'Australia/Sydney' },
  { value: 'Europe/Amsterdam', label: 'Europe/Amsterdam (Netherlands)' },
  { value: 'Europe/Athens', label: 'Europe/Athens (Greece)' },
  { value: 'Europe/Berlin', label: 'Europe/Berlin (Germany)' },
  { value: 'Europe/Brussels', label: 'Europe/Brussels (Belgium)' },
  { value: 'Europe/Budapest', label: 'Europe/Budapest (Hungary)' },
  { value: 'Europe/Dublin', label: 'Europe/Dublin (Ireland)' },
  { value: 'Europe/Istanbul', label: 'Europe/Istanbul (Türkiye)' },
  { value: 'Europe/Kyiv', label: 'Europe/Kyiv (Ukraine)' },
  { value: 'Europe/Lisbon', label: 'Europe/Lisbon (Portugal)' },
  { value: 'Europe/London', label: 'Europe/London (United Kingdom)' },
  { value: 'Europe/Madrid', label: 'Europe/Madrid (Spain)' },
  { value: 'Europe/Moscow', label: 'Europe/Moscow (Russia)' },
  { value: 'Europe/Paris', label: 'Europe/Paris (France)' },
  { value: 'Europe/Prague', label: 'Europe/Prague (Czechia)' },
  { value: 'Europe/Rome', label: 'Europe/Rome (Italy)' },
  { value: 'Europe/Vienna', label: 'Europe/Vienna (Austria)' },
  { value: 'Europe/Warsaw', label: 'Europe/Warsaw (Poland)' },
  { value: 'Pacific/Guam', label: 'Pacific/Guam' },
  { value: 'Pacific/Honolulu', label: 'Pacific/Honolulu (Hawaii)' },
  { value: 'Pacific/Auckland', label: 'Pacific/Auckland (New Zealand)' },
  { value: 'Pacific/Port_Moresby', label: 'Pacific/Port_Moresby (Papua New Guinea)' },
].sort((a, b) => a.label.localeCompare(b.label));

/** If the tenant already has a value outside the curated list, show it so saves stay backward-compatible. */
export function mergeSelectedOption(
  options: { value: string; label: string }[],
  selected: string | undefined,
): { value: string; label: string }[] {
  if (!selected || options.some((o) => o.value === selected)) {
    return options;
  }
  return [{ value: selected, label: `${selected} (current)` }, ...options];
}
