import { useEffect, useState } from 'react';
import { apiClient } from '@farm-erp/shared';
import { exportToCSV } from '../utils/csvExport';
import { useFormatting } from '../hooks/useFormatting';
import { LoadingSpinner } from '../components/LoadingSpinner';
import { DataTable, type Column } from '../components/DataTable';
import { PrintableReport } from '../components/print/PrintableReport';

interface CashbookRow {
  date: string;
  description: string;
  reference: string;
  type: 'IN' | 'OUT';
  amount: string;
  source_type: string;
  source_id: string;
}

export default function CashbookPage() {
  const { formatMoney, formatDate } = useFormatting();
  const [data, setData] = useState<CashbookRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  
  const [filters, setFilters] = useState({
    from: new Date(new Date().getFullYear(), 0, 1).toISOString().split('T')[0],
    to: new Date().toISOString().split('T')[0],
  });

  useEffect(() => {
    const fetchData = async () => {
      if (!filters.from || !filters.to) return;
      
      try {
        setLoading(true);
        setError(null);
        
        const result = await apiClient.get<CashbookRow[]>(`/api/reports/cashbook?from=${filters.from}&to=${filters.to}`);
        setData(result);
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Failed to fetch cashbook');
      } finally {
        setLoading(false);
      }
    };

    fetchData();
  }, [filters]);

  const handleExport = () => {
    exportToCSV(
      data,
      '', // Filename will be generated by Terrava format
      ['date', 'description', 'reference', 'type', 'amount'],
      {
        reportName: 'Cashbook',
        fromDate: filters.from,
        toDate: filters.to,
      }
    );
  };

  const columns: Column<CashbookRow>[] = [
    { header: 'Date', accessor: (row) => formatDate(row.date) },
    { header: 'Description', accessor: 'description' },
    { header: 'Reference', accessor: 'reference' },
    { 
      header: 'Type', 
      accessor: (row) => (
        <span className={`px-2 py-1 rounded text-xs ${
          row.type === 'IN' ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'
        }`}>
          {row.type}
        </span>
      )
    },
    { 
      header: 'Amount', 
      accessor: (row) => <span className="tabular-nums text-right block">{formatMoney(parseFloat(row.amount || '0'))}</span>
    },
  ];

  const totalIn = data
    .filter(row => row.type === 'IN')
    .reduce((sum, row) => sum + parseFloat(row.amount || '0'), 0);
  
  const totalOut = data
    .filter(row => row.type === 'OUT')
    .reduce((sum, row) => sum + parseFloat(row.amount || '0'), 0);
  
  const netBalance = totalIn - totalOut;

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center no-print">
        <h2 className="text-2xl font-bold">Cashbook</h2>
        <div className="flex gap-2">
          <button
            onClick={() => window.print()}
            className="bg-[#1F6F5C] text-white px-4 py-2 rounded hover:bg-[#1a5a4a] text-sm font-medium"
          >
            Print
          </button>
          <button
            onClick={handleExport}
            disabled={data.length === 0}
            className="bg-[#1F6F5C] text-white px-4 py-2 rounded hover:bg-[#1a5a4a] disabled:bg-gray-400 disabled:cursor-not-allowed text-sm font-medium"
          >
            Export CSV
          </button>
        </div>
      </div>

      <div className="bg-white p-4 rounded-lg shadow space-y-4 no-print">
        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              From Date
            </label>
            <input
              type="date"
              value={filters.from}
              onChange={(e) => setFilters({ ...filters, from: e.target.value })}
              className="w-full px-3 py-2 border border-gray-300 rounded-md"
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              To Date
            </label>
            <input
              type="date"
              value={filters.to}
              onChange={(e) => setFilters({ ...filters, to: e.target.value })}
              className="w-full px-3 py-2 border border-gray-300 rounded-md"
            />
          </div>
        </div>
      </div>

      {error && (
        <div className="bg-red-50 border border-red-200 text-red-800 px-4 py-3 rounded">
          {error}
        </div>
      )}

      {loading ? (
        <div className="flex justify-center py-12">
          <LoadingSpinner size="lg" />
        </div>
      ) : (
        <>
          {/* Screen view */}
          <div className="bg-white rounded-lg shadow no-print">
            <DataTable 
              data={data.map((r, i) => ({ ...r, id: r.source_id || String(i) }))} 
              columns={columns} 
            />
            {data.length > 0 && (
              <div className="p-4 bg-gray-50 border-t totals-row">
                <div className="grid grid-cols-4 gap-4 text-sm font-medium">
                  <div>Total In: <span className="tabular-nums">{formatMoney(totalIn)}</span></div>
                  <div>Total Out: <span className="tabular-nums">{formatMoney(totalOut)}</span></div>
                  <div>Net Balance: <span className="tabular-nums">{formatMoney(netBalance)}</span></div>
                  <div>Transactions: {data.length}</div>
                </div>
              </div>
            )}
          </div>

          {/* Print view */}
          <PrintableReport
            title="Cashbook"
            metaLeft={`From ${formatDate(filters.from)} to ${formatDate(filters.to)}`}
          >
            <table className="w-full divide-y divide-gray-200">
              <thead className="bg-[#E6ECEA]">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Date</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Description</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Reference</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Type</th>
                  <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">Amount</th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {data.length === 0 ? (
                  <tr>
                    <td colSpan={5} className="px-6 py-4 text-center text-gray-500">No data found</td>
                  </tr>
                ) : (
                  data.map((row, i) => (
                    <tr key={row.source_id || String(i)}>
                      <td className="px-6 py-4 text-sm text-gray-900">{formatDate(row.date)}</td>
                      <td className="px-6 py-4 text-sm text-gray-500">{row.description}</td>
                      <td className="px-6 py-4 text-sm text-gray-500">{row.reference}</td>
                      <td className="px-6 py-4 text-sm text-gray-500">{row.type}</td>
                      <td className="px-6 py-4 text-sm text-gray-900 text-right">
                        <span className="tabular-nums">{formatMoney(parseFloat(row.amount || '0'))}</span>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
              {data.length > 0 && (
                <tfoot>
                  <tr className="print-total-row totals-row bg-gray-50 font-semibold print-avoid-break">
                    <td colSpan={1} className="px-6 py-4 text-sm text-gray-900">Total In:</td>
                    <td className="px-6 py-4 text-sm text-gray-900 text-right" colSpan={4}>
                      <span className="tabular-nums">{formatMoney(totalIn)}</span>
                    </td>
                  </tr>
                  <tr className="print-total-row totals-row bg-gray-50 font-semibold print-avoid-break">
                    <td colSpan={1} className="px-6 py-4 text-sm text-gray-900">Total Out:</td>
                    <td className="px-6 py-4 text-sm text-gray-900 text-right" colSpan={4}>
                      <span className="tabular-nums">{formatMoney(totalOut)}</span>
                    </td>
                  </tr>
                  <tr className="print-total-row totals-row bg-gray-50 font-semibold print-avoid-break">
                    <td colSpan={1} className="px-6 py-4 text-sm text-gray-900">Net Balance:</td>
                    <td className="px-6 py-4 text-sm text-gray-900 text-right" colSpan={4}>
                      <span className="tabular-nums">{formatMoney(netBalance)}</span>
                    </td>
                  </tr>
                </tfoot>
              )}
            </table>
          </PrintableReport>
        </>
      )}
    </div>
  );
}
