import { useEffect, useState } from 'react'
import { CropCyclePLRow, CropCycle, apiClient } from '@farm-erp/shared'
import { exportToCSV } from '../utils/csvExport'
import { useFormatting } from '../hooks/useFormatting'
import { PrintableReport } from '../components/print/PrintableReport'

function CropCyclePLPage() {
  const { formatMoney, formatDate } = useFormatting()
  const [data, setData] = useState<CropCyclePLRow[]>([])
  const [cropCycles, setCropCycles] = useState<CropCycle[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  
  const [filters, setFilters] = useState({
    from: new Date(new Date().getFullYear(), 0, 1).toISOString().split('T')[0],
    to: new Date().toISOString().split('T')[0],
    crop_cycle_id: '',
  })

  useEffect(() => {
    const fetchCropCycles = async () => {
      try {
        // Note: Assuming there's a crop cycles endpoint, otherwise fetch from projects
        const cyclesData = await apiClient.get<CropCycle[]>('/api/crop-cycles').catch(() => [])
        setCropCycles(cyclesData)
      } catch (err) {
        console.error('Failed to fetch crop cycles', err)
      }
    }
    fetchCropCycles()
  }, [])

  useEffect(() => {
    const fetchData = async () => {
      if (!filters.from || !filters.to) return
      
      try {
        setLoading(true)
        setError(null)
        
        const result = await apiClient.getCropCyclePL({
          from: filters.from,
          to: filters.to,
          crop_cycle_id: filters.crop_cycle_id || undefined,
        })
        setData(result)
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Failed to fetch crop cycle P&L')
      } finally {
        setLoading(false)
      }
    }

    fetchData()
  }, [filters])

  const handleExport = () => {
    exportToCSV(
      data,
      '', // Filename will be generated by Terrava format
      ['crop_cycle_id', 'crop_cycle_name', 'currency_code', 'income', 'expenses', 'net_profit'],
      {
        reportName: 'CropCyclePL',
        fromDate: filters.from,
        toDate: filters.to,
      }
    )
  }

  // Calculate totals
  const totals = data.reduce(
    (acc, row) => ({
      income: acc.income + parseFloat(row.income),
      expenses: acc.expenses + parseFloat(row.expenses),
      net_profit: acc.net_profit + parseFloat(row.net_profit),
    }),
    { income: 0, expenses: 0, net_profit: 0 }
  )

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center no-print">
        <h2 className="text-2xl font-bold">Crop Cycle P&L</h2>
        <div className="flex gap-2">
          <button
            onClick={() => window.print()}
            className="bg-[#1F6F5C] text-white px-4 py-2 rounded hover:bg-[#1a5a4a] text-sm font-medium"
          >
            Print
          </button>
          <button
            onClick={handleExport}
            disabled={data.length === 0}
            className="bg-[#1F6F5C] text-white px-4 py-2 rounded hover:bg-[#1a5a4a] disabled:bg-gray-400 disabled:cursor-not-allowed text-sm font-medium"
          >
            Export CSV
          </button>
        </div>
      </div>

      <div className="bg-white p-4 rounded-lg shadow space-y-4 no-print">
        <div className="grid grid-cols-3 gap-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              From Date
            </label>
            <input
              type="date"
              value={filters.from}
              onChange={(e) => setFilters({ ...filters, from: e.target.value })}
              className="w-full border border-gray-300 rounded px-3 py-2"
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              To Date
            </label>
            <input
              type="date"
              value={filters.to}
              onChange={(e) => setFilters({ ...filters, to: e.target.value })}
              className="w-full border border-gray-300 rounded px-3 py-2"
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Crop Cycle
            </label>
            <select
              value={filters.crop_cycle_id}
              onChange={(e) => setFilters({ ...filters, crop_cycle_id: e.target.value })}
              className="w-full border border-gray-300 rounded px-3 py-2"
            >
              <option value="">All Crop Cycles</option>
              {cropCycles.map((cc) => (
                <option key={cc.id} value={cc.id}>
                  {cc.name}
                </option>
              ))}
            </select>
          </div>
        </div>
      </div>

      {loading && <div className="text-center py-8">Loading...</div>}
      {error && <div className="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded">{error}</div>}

      {!loading && !error && (
        <>
          {/* Screen view */}
          <div className="bg-white rounded-lg shadow overflow-hidden no-print">
            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-gray-200">
                <thead className="bg-[#E6ECEA]">
                  <tr>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Crop Cycle
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Currency
                    </th>
                    <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Income
                    </th>
                    <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Expenses
                    </th>
                    <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Net Profit
                    </th>
                  </tr>
                </thead>
                <tbody className="bg-white divide-y divide-gray-200">
                  {data.length === 0 ? (
                    <tr>
                      <td colSpan={5} className="px-6 py-4 text-center text-gray-500">
                        No data found
                      </td>
                    </tr>
                  ) : (
                    <>
                      {data.map((row) => (
                        <tr key={`${row.crop_cycle_id}-${row.currency_code}`}>
                          <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                            {row.crop_cycle_name}
                          </td>
                          <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                            {row.currency_code}
                          </td>
                          <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900 text-right">
                            <span className="tabular-nums">{formatMoney(row.income)}</span>
                          </td>
                          <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900 text-right">
                            <span className="tabular-nums">{formatMoney(row.expenses)}</span>
                          </td>
                          <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 text-right">
                            <span className="tabular-nums">{formatMoney(row.net_profit)}</span>
                          </td>
                        </tr>
                      ))}
                      {data.length > 0 && (
                        <tr className="totals-row bg-gray-50 font-semibold">
                          <td colSpan={2} className="px-6 py-4 text-sm text-gray-900">
                            Total
                          </td>
                          <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900 text-right">
                            <span className="tabular-nums">{formatMoney(totals.income)}</span>
                          </td>
                          <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900 text-right">
                            <span className="tabular-nums">{formatMoney(totals.expenses)}</span>
                          </td>
                          <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900 text-right">
                            <span className="tabular-nums">{formatMoney(totals.net_profit)}</span>
                          </td>
                        </tr>
                      )}
                    </>
                  )}
                </tbody>
              </table>
            </div>
          </div>

          {/* Print view */}
          <PrintableReport
            title="Crop Cycle P&L"
            metaLeft={`From ${formatDate(filters.from)} to ${formatDate(filters.to)}`}
          >
            <table className="w-full divide-y divide-gray-200">
              <thead className="bg-[#E6ECEA]">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Crop Cycle
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Currency
                  </th>
                  <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Income
                  </th>
                  <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Expenses
                  </th>
                  <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Net Profit
                  </th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {data.length === 0 ? (
                  <tr>
                    <td colSpan={5} className="px-6 py-4 text-center text-gray-500">
                      No data found
                    </td>
                  </tr>
                ) : (
                  <>
                    {data.map((row) => (
                      <tr key={`${row.crop_cycle_id}-${row.currency_code}`}>
                        <td className="px-6 py-4 text-sm font-medium text-gray-900">
                          {row.crop_cycle_name}
                        </td>
                        <td className="px-6 py-4 text-sm text-gray-500">
                          {row.currency_code}
                        </td>
                        <td className="px-6 py-4 text-sm text-gray-900 text-right">
                          <span className="tabular-nums">{formatMoney(row.income)}</span>
                        </td>
                        <td className="px-6 py-4 text-sm text-gray-900 text-right">
                          <span className="tabular-nums">{formatMoney(row.expenses)}</span>
                        </td>
                        <td className="px-6 py-4 text-sm font-medium text-gray-900 text-right">
                          <span className="tabular-nums">{formatMoney(row.net_profit)}</span>
                        </td>
                      </tr>
                    ))}
                    {data.length > 0 && (
                      <tr className="print-total-row totals-row bg-gray-50 font-semibold print-avoid-break">
                        <td colSpan={2} className="px-6 py-4 text-sm text-gray-900">
                          Total
                        </td>
                        <td className="px-6 py-4 text-sm text-gray-900 text-right">
                          <span className="tabular-nums">{formatMoney(totals.income)}</span>
                        </td>
                        <td className="px-6 py-4 text-sm text-gray-900 text-right">
                          <span className="tabular-nums">{formatMoney(totals.expenses)}</span>
                        </td>
                        <td className="px-6 py-4 text-sm text-gray-900 text-right">
                          <span className="tabular-nums">{formatMoney(totals.net_profit)}</span>
                        </td>
                      </tr>
                    )}
                  </>
                )}
              </tbody>
            </table>
          </PrintableReport>
        </>
      )}
    </div>
  )
}

export default CropCyclePLPage
